#!/usr/bin/env python3
"""Render target boot configuration into a new staging directory."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile
from typing import Any
import uuid

from install import plan


ESP_UUID_PATTERN = re.compile(r"^[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}$")
PLACEHOLDER_ROOT_UUID = "00000000-0000-4000-8000-000000000001"
PLACEHOLDER_LUKS_UUID = "00000000-0000-4000-8000-000000000002"
PLACEHOLDER_ESP_UUID = "0000-0001"
PROTECTED_OUTPUT_ROOTS = tuple(
    Path(path)
    for path in ("/boot", "/dev", "/etc", "/proc", "/run", "/sys", "/usr", "/var")
)


class RenderError(ValueError):
    """Raised when target configuration cannot be rendered safely."""


def canonical_uuid(value: str | None, label: str) -> str:
    if not value:
        raise RenderError(f"{label} is required")
    try:
        return str(uuid.UUID(value))
    except ValueError as error:
        raise RenderError(f"{label} must be a UUID") from error


def canonical_esp_uuid(value: str | None) -> str:
    if not value:
        raise RenderError("ESP UUID is required")
    if not ESP_UUID_PATTERN.fullmatch(value):
        raise RenderError("ESP UUID must use the FAT XXXX-XXXX format")
    return value.upper()


def resolve_identifiers(
    *,
    root_uuid: str | None,
    esp_uuid: str | None,
    luks_uuid: str | None,
    encrypted: bool,
    placeholders: bool,
) -> dict[str, str | None]:
    if placeholders:
        if any(value is not None for value in (root_uuid, esp_uuid, luks_uuid)):
            raise RenderError("--placeholders cannot be combined with UUID arguments")
        return {
            "root_uuid": PLACEHOLDER_ROOT_UUID,
            "esp_uuid": PLACEHOLDER_ESP_UUID,
            "luks_uuid": PLACEHOLDER_LUKS_UUID if encrypted else None,
        }

    if not encrypted and luks_uuid is not None:
        raise RenderError("LUKS UUID is only valid when encryption is enabled")

    return {
        "root_uuid": canonical_uuid(root_uuid, "root filesystem UUID"),
        "esp_uuid": canonical_esp_uuid(esp_uuid),
        "luks_uuid": (
            canonical_uuid(luks_uuid, "LUKS UUID") if encrypted else None
        ),
    }


def render_fstab(config: dict[str, Any], root_uuid: str, esp_uuid: str) -> str:
    storage = plan.require_table(config, "storage")
    btrfs = plan.require_table(storage, "btrfs")
    mount_options = list(btrfs["mount_options"])
    if "rw" not in mount_options and "ro" not in mount_options:
        mount_options.insert(0, "rw")

    lines = [
        "# Generated by Utopia. Review install/config.example.toml before editing.",
        "# <file system> <dir> <type> <options> <dump> <pass>",
    ]
    for subvolume in btrfs["subvolumes"]:
        options = mount_options + [f"subvol=/{subvolume['name']}"]
        lines.append(
            f"UUID={root_uuid}\t{subvolume['mountpoint']}\tbtrfs\t"
            f"{','.join(options)}\t0 0"
        )
    lines.extend(
        [
            f"UUID={esp_uuid}\t/boot\tvfat\t"
            "rw,relatime,fmask=0022,dmask=0022,codepage=437,"
            "iocharset=ascii,shortname=mixed,utf8,errors=remount-ro\t0 2",
            "",
        ]
    )
    return "\n".join(lines)


def render_mkinitcpio_dropin(hooks: list[str]) -> str:
    return "\n".join(
        [
            "# Generated by Utopia. Keep encryption hooks out of the base profile.",
            f"HOOKS=({' '.join(hooks)})",
            "",
        ]
    )


def render_mkinitcpio_preset(kernel: str, fallback: bool) -> str:
    presets = "'default' 'fallback'" if fallback else "'default'"
    lines = [
        "# Generated by Utopia for the selected kernel.",
        f'ALL_kver="/boot/vmlinuz-{kernel}"',
        f"PRESETS=({presets})",
        f'default_image="/boot/initramfs-{kernel}.img"',
    ]
    if fallback:
        lines.extend(
            [
                f'fallback_image="/boot/initramfs-{kernel}-fallback.img"',
                'fallback_options="-S autodetect"',
            ]
        )
    lines.append("")
    return "\n".join(lines)


def render_limine(kernel: str, cmdline: str) -> str:
    return "\n".join(
        [
            "/Arch Linux",
            "  protocol: linux",
            f"  path: boot():/vmlinuz-{kernel}",
            f"  module_path: boot():/initramfs-{kernel}.img",
            f"  cmdline: {cmdline}",
            "",
        ]
    )


def resolved_config(
    config: dict[str, Any], *, encryption_override: bool | None
) -> tuple[dict[str, Any], dict[str, Any]]:
    install_plan = plan.build_plan(
        config,
        plan.REPO_ROOT,
        device_override="/dev/utopia-render-target",
        encryption_override=encryption_override,
        probe_device=False,
    )
    return config, install_plan


def build_artifacts(
    config: dict[str, Any],
    *,
    root_uuid: str | None,
    esp_uuid: str | None,
    luks_uuid: str | None,
    encryption_override: bool | None,
    placeholders: bool,
) -> tuple[dict[str, str], dict[str, Any]]:
    _, install_plan = resolved_config(
        config, encryption_override=encryption_override
    )
    encrypted = install_plan["storage"]["encryption"]
    identifiers = resolve_identifiers(
        root_uuid=root_uuid,
        esp_uuid=esp_uuid,
        luks_uuid=luks_uuid,
        encrypted=encrypted,
        placeholders=placeholders,
    )
    root_id = str(identifiers["root_uuid"])
    esp_id = str(identifiers["esp_uuid"])
    cmdline = install_plan["boot"]["kernel_cmdline_template"].replace(
        "<BTRFS_UUID>", root_id
    )
    if encrypted:
        cmdline = cmdline.replace("<LUKS_UUID>", str(identifiers["luks_uuid"]))

    boot = plan.require_table(config, "boot")
    kernel = boot["kernel"]
    hooks = install_plan["boot"]["mkinitcpio_hooks"]
    artifacts = {
        "etc/fstab": render_fstab(config, root_id, esp_id),
        "etc/mkinitcpio.conf.d/utopia.conf": render_mkinitcpio_dropin(hooks),
        f"etc/mkinitcpio.d/{kernel}.preset": render_mkinitcpio_preset(
            kernel, boot["fallback_initramfs"]
        ),
        "boot/limine.conf": render_limine(kernel, cmdline),
    }
    metadata = {
        "encryption": encrypted,
        "identifiers": identifiers,
        "files": sorted(artifacts),
    }
    return artifacts, metadata


def validate_output_directory(output: Path) -> Path:
    resolved = output.expanduser().resolve()
    if resolved == Path("/"):
        raise RenderError("output directory cannot be the filesystem root")
    for protected in PROTECTED_OUTPUT_ROOTS:
        if resolved == protected or protected in resolved.parents:
            raise RenderError(f"refusing to render inside live system path: {protected}")
    if resolved.exists():
        raise RenderError("output directory already exists; choose a new staging path")
    if not resolved.parent.is_dir():
        raise RenderError(f"output parent does not exist: {resolved.parent}")
    return resolved


def write_artifacts(output: Path, artifacts: dict[str, str]) -> list[Path]:
    destination = validate_output_directory(output)
    staging = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.", dir=destination.parent)
    )
    try:
        for relative_path, content in artifacts.items():
            target = staging / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            target.chmod(0o644)
        staging.rename(destination)
    except Exception:
        shutil.rmtree(staging)
        raise
    return [destination / relative_path for relative_path in sorted(artifacts)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Render Utopia boot configuration into a new staging directory."
    )
    parser.add_argument(
        "config",
        nargs="?",
        type=Path,
        default=plan.DEFAULT_CONFIG,
        help="TOML profile (default: install/config.example.toml)",
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--root-uuid")
    parser.add_argument("--esp-uuid")
    parser.add_argument("--luks-uuid")
    parser.add_argument(
        "--encryption",
        choices=("on", "off"),
        help="override storage.encryption for this render",
    )
    parser.add_argument(
        "--placeholders",
        action="store_true",
        help="use deterministic non-secret UUID placeholders",
    )
    parser.add_argument("--json", action="store_true", help="emit JSON metadata")
    args = parser.parse_args(argv)

    try:
        config = plan.load_config(args.config)
        artifacts, metadata = build_artifacts(
            config,
            root_uuid=args.root_uuid,
            esp_uuid=args.esp_uuid,
            luks_uuid=args.luks_uuid,
            encryption_override=plan.parse_encryption_override(args.encryption),
            placeholders=args.placeholders,
        )
        files = write_artifacts(args.output, artifacts)
        output = args.output.expanduser().resolve()
        if args.json:
            print(
                json.dumps(
                    {
                        "output": os.fspath(output),
                        **metadata,
                    },
                    indent=2,
                )
            )
        else:
            print(f"Rendered {len(files)} files under {output}:")
            for path in files:
                print(f"  {path.relative_to(output)}")
            print("No live system files were changed.")
        return 0
    except (plan.PlanError, RenderError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
